### ISSUE TITLE
EC2 tutorial

### ISSUE THREAD

**Issue by miohtama** [liangshan/drill-ansible#2]
Hi,

I wrote this little tutorial using this playbook on EC2:

https://opensourcehacker.com/2015/04/12/almost-free-netflix-vpn-on-amazon-ec2-set-up-in-30-minutes-using-ansible/

You'll get a good deal as you can use on demand instances, pay by the go by hours.

Maybe link it from README?

**Comment by liangshan** [comment]
Sure, it's kind of how to use this ansible playbook from sketch. I'd love to add this link.

**Comment by liangshan** [comment]
Added.
If this is OK for you, please close this issue after review.

**Comment by miohtama** [comment]
:+1:
